### ISSUE TITLE
TypeError: Toggl is not a constructor

### ISSUE THREAD

**Issue by zjor** [garyhtou/toggl-track#1]
Hi, I have the following code
```
import Toggl from 'toggl-track';

const toggl = new Toggl({
    auth: {
        token: '',
    },
});
```
and I'm getting this error
```
const toggl = new Toggl({
              ^

TypeError: Toggl is not a constructor

```
where might be the issue?

Node version: v16.14.0

"toggl-track": "^0.7.1"

Thanks in advance!

**Comment by xstable** [comment]
There are two issues in the example-code. Use those for testing:
```JS
import {Toggl} from 'toggl-track';

const toggl = new Toggl({
  auth: {
    token: process.env.TOGGL_TRACK_API_TOKEN,
  },
});

const entries = await toggl.timeEntry.list();
console.log(entries);
```
Don't miss to set the ENV-Variable TOGGL_TRACK_API_TOKEN with your toggl-token.

**Comment by zjor** [comment]
Thanks! That helped!
