### ISSUE TITLE
Trailing slash causes 404

### ISSUE THREAD

**Issue by vandermerwed** [garyhtou/toggl-track#3]
https://github.com/garyhtou/toggl-track/blob/56e9f12a002d775108c24ac89493f7416917647b/src/timeEntry.ts#L46

![image](https://user-images.githubusercontent.com/8472841/186073876-86be8b74-ecab-43c2-8077-311a08a0a4be.png)

![image](https://user-images.githubusercontent.com/8472841/186074135-7b2b5d7b-c9f8-43ff-85d1-d310c5d76c04.png)

**Comment by garyhtou** [comment]
Thanks for catching this @vandermerwed!
