### ISSUE TITLE
Clients

### ISSUE THREAD

**Issue by spassvogel** [garyhtou/toggl-track#9]
Would be very nice if this API supported the clients endpoint

**Comment by garyhtou** [comment]
Hey @spassvogel, great suggestion! If you'd like, feel free to open a PR.

It would involve adding a new `clients.ts` file (based on the API docs) to [`/src`](https://github.com/garyhtou/toggl-track/tree/main/src) and exporting it in [`/src/index.ts`](https://github.com/garyhtou/toggl-track/blob/main/src/index.ts). I'd be happy to provide some guidance 😊
